### PR TITLE
Create swagger.json for documentation

### PR DESCRIPTION
**Pull request by iagocavalcante**
I created a folder called api and created a file inside, this file is swagger.yaml and can be edited with swagger project edit, for use this, just install npm install swagger -g and run swagger project edit inside of the project folder or if you are acquainted with swagger specification, just edit swagger.json inside src/interfaces/http/utils/swagger.

For you see the docs, type http://localhost:3000/api-docs in your favorite browser.

### CODE REVIEW

**Comment by talyssonoc** [comment]
Hey, @iagocavalcante, thanks for your contribution!

Before merging I think we need some changes on the PR to make it fit the standards we're using in the project:

- It would be good to have `swagger` as a dev dependency instead of having to install it globally;
- Both `swagger-ui-express` and `swagger` must be installed with `yarn` in order to have it in `yarn.lock`;
- There should be an alias to `swagger` in the package.json `scripts`. You should add it before the `cleanup` script. It can be as simple as `"swagger": "swagger"` so we can run `npm run swagger project edit` instead of having to use the global;
- Looks like we have two manifesto files for Swagger right now, one being an YAML inside `api/swagger` and the other inside `src/interfaces/http/utils/swagger`. We should have a single one, and I recommend putting it inside `src/interfaces/http/swagger` (without the `utils` part);
- It says that the title of the API is "API Phalcom ATM", this should be "Node API boilerplate";
- In the `router.js` file you're using a single `var` for the Swagger imports. Can we use a `const` for each of them to match the rest of the file;
- Can we use two spaces indentation instead of four in the JSON file?

Let me know if you have the time to work on these changes, otherwise, I can work on them as well.

**Comment by iagocavalcante** [comment]
I can work on these change just in this weekend, if no hava problem!

**Comment by talyssonoc** [comment]
@iagocavalcante I'll try to work on it during the week, if I didn't finish you can continue on that (I'm gonna check the ones I completed). Thanks!

**Comment by iagocavalcante** [comment]
Okay, sorry for this mistakes!

**Comment by talyssonoc** [comment]
No problem at all! 😄

**Pull request closed without merging**
